### ISSUE TITLE
PersonResource: Postgres parameter limit exceeded

### ISSUE THREAD

**Issue by HolgerReiseVSys** [SORMAS-Foundation/SORMAS-Project#11186]
### Problem Description

When providing over 70,000 person uuids for retrieving persons via the `persons/query` REST endpoint, a PSQLException occurs.

PSQLException: PreparedStatement can have at most 65.535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 71.827 parameters

Cleaned  stack trace:
```
javax.transaction.TransactionRolledbackException: CORBA TRANSACTION_ROLLEDBACK 9998 Maybe&#59; nested exception is: 
org.omg.CORBA.TRANSACTION_ROLLEDBACK: ----------BEGIN server-side stack trace----------
org.omg.CORBA.TRANSACTION_ROLLEDBACK:   vmcid: 0x2000  minor code: 1806 completed: Maybe
at de.symeda.sormas.api.person.__PersonFacade_Remote_DynamicStub.getByUuids(de/symeda/sormas/api/person/__PersonFacade_Remote_DynamicStub.java)
at de.symeda.sormas.api.person._PersonFacade_Wrapper.getByUuids(de/symeda/sormas/api/person/_PersonFacade_Wrapper.java)
at de.symeda.sormas.rest.PersonResource.getByUuids(PersonResource.java:78)
at de.symeda.sormas.rest.PersonResource$Proxy$_$$_WeldSubclass.getByUuids(Unknown Source)
at de.symeda.sormas.rest.security.KeycloakFilter.doFilter(KeycloakFilter.java:63)
at de.symeda.sormas.rest.SessionFilter.lambda$doFilter$0(SessionFilter.java:55)
at de.symeda.sormas.rest.SessionFilterBean.doFilter(SessionFilterBean.java:37)
at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
at de.symeda.sormas.rest.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
at de.symeda.sormas.rest.SessionFilter.doFilter(SessionFilter.java:50)
at de.symeda.sormas.rest.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
at de.symeda.sormas.rest.logging.RequestResponseLogger.doFilter(RequestResponseLogger.java:94)
... 124 more
Caused by: javax.ejb.EJBTransactionRolledbackException: Exception thrown from bean: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not prepare statement
at de.symeda.sormas.backend.person.__EJB31_Generated__PersonService__Intf____Bean__.getByUuids(Unknown Source)
at de.symeda.sormas.backend.person.PersonFacadeEjb.getByUuids(PersonFacadeEjb.java:280)
at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:35)
at de.symeda.sormas.backend.util.RightsAllowedInterceptor.checkRightsAllowed(RightsAllowedInterceptor.java:111)
at de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:37)
at de.symeda.sormas.backend.audit.AuditLoggerInterceptor.logAudit(AuditLoggerInterceptor.java:78)
at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
... 122 more
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not prepare statement
... 185 more
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not prepare statement
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
at org.hibernate.query.Query.getResultList(Query.java:165)
at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
at de.symeda.sormas.backend.common.BaseAdoService.getByUuids(BaseAdoService.java:265)
at de.symeda.sormas.backend.util.ValidationConstraintViolationInterceptor.handleValidationConstraintViolation(ValidationConstraintViolationInterceptor.java:35)
at de.symeda.sormas.backend.util.RightsAllowedInterceptor.checkRightsAllowed(RightsAllowedInterceptor.java:111)
at de.symeda.sormas.backend.util.PerformanceLoggingInterceptor.logInvokeDuration(PerformanceLoggingInterceptor.java:37)
at de.symeda.sormas.backend.audit.AuditLoggerInterceptor.logAudit(AuditLoggerInterceptor.java:78)
at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
... 183 more
Caused by: org.hibernate.exception.GenericJDBCException: could not prepare statement
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
at org.hibernate.loader.Loader.doQuery(Loader.java:956)
at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
at org.hibernate.loader.Loader.doList(Loader.java:2868)
at org.hibernate.loader.Loader.doList(Loader.java:2850)
at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
at org.hibernate.loader.Loader.list(Loader.java:2677)
at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1454)
at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
... 243 more
Caused by: java.sql.SQLException: java.lang.reflect.UndeclaredThrowableException
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
... 259 more
Caused by: java.lang.reflect.UndeclaredThrowableException
... 261 more
Caused by: java.lang.reflect.InvocationTargetException
... 267 more
Caused by: org.postgresql.util.PSQLException: PreparedStatement can have at most 65.535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 71.827 parameters
at org.postgresql.jdbc.PgPreparedStatement.&lt;init&gt;(PgPreparedStatement.java:102)
at org.postgresql.jdbc.PgPreparedStatement.&lt;init&gt;(PgPreparedStatement.java:88)
at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1325)
at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1779)
at org.postgresql.ds.PGPooledConnection$ConnectionHandler.invoke(PGPooledConnection.java:343)
... 271 more
```

#### Steps to Reproduce

1.
2.

#### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

**Comment by JonasCir** [comment]
Now I'm curious, what did you do trigger this? Just a get all operation or did you actually filter for something? :D

**Comment by HolgerReiseVSys** [comment]
@JonasCir This could be triggered e.g. by POSTing a JSON array with 70.000 UUIDs to the /persons/query endpoint
