### ISSUE TITLE
Add tested pathogen attribute to pathogen test [3]

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11582]
### Feature Description

This issue is part of the EPIC https://github.com/hzi-braunschweig/SORMAS-Project/issues/11533 on the environmental surveillance module. Environment samples are tested for multiple pathogens and not for specific diseases; therefore, pathogen tests need to be extended to have a "Tested pathogen" attribute.

### Acceptance Criteria

- [x] A "Tested pathogen" field has been added to pathogen tests in both the web and mobile app, containing all pathogens in the customizable enum table
- [x] The new field is shown in pathogen test forms for pathogen tests linked to environment samples; it is hidden for normal samples; vice versa, the "Tested disease" field is hidden for pathogen tests linked to environment samples
- [x] The field is mandatory for environment samples
- [x] The following columns introduced in #11566 have been implemented:
  - Positive pathogen tests: A list of all tested pathogens of all pathogen tests related to the environment sample with a positive laboratory result
  - Latest pathogen test: The tested pathogen and result of the latest pathogen test linked to the environment sample
- [x] Add a new line to the environment samples list in the mobile app containing the pathogens that the sample has been positively tested for
- [x] The tested pathogen filter in the environment sample grid has been properly implemented (i.e. it shows all environment sample with at least one pathogen test with the specified tested pathogen)

### Additional Information

![PATHOGEN TEST FORM](https://user-images.githubusercontent.com/12996724/230210202-84982afa-e631-43c5-a83a-b69f39dab999.png)

**Comment by bernardsilenou** [comment]
@MateStrysewske 
I initially thought the same because both attributes are highly correlated. However,
1. The enum names can be different, eg disease == Cholera but pathogen == Vibro CholeraeVibro
2. Pathogen implies disease but not necessarily the other way around. eg disease == malaria, pathogen = Plasmodium Vivax, p falciparum, p malaria
3. Since some samples may be collected from the environment, the team may be interested in testing for pathogens that we do not have the corresponding disease in SORMAS.
4. The list of pathogens ([pathogen_diseases_env.ods](https://github.com/hzi-braunschweig/SORMAS-Project/files/11212941/pathogen_diseases_env.ods)) from env is very long, including diseases affecting animals, so it may be too much for users who are not responsible for managing env samples.

**Comment by abrudanancuta** [comment]
This ticket will be reopened because a pathogen test cannot be added from the Sample pop-up.
I attach also the logs: `Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc (de.symeda.sormas.ui.SormasErrorHandler.java:85)
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method click in com.vaadin.shared.ui.button.ButtonServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:442)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:407)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:275)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1637)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1637)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at de.symeda.sormas.ui.Slf4jMdcFilter.doFilter(Slf4jMdcFilter.java:29)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at de.symeda.sormas.ui.SessionFilter.lambda$doFilter$2(SessionFilter.java:73)
	at de.symeda.sormas.ui.SessionFilterBean.doFilter(SessionFilterBean.java:37)
	at jdk.internal.reflect.GeneratedMethodAccessor834.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4835)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor268.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor230.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4807)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4795)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy916.doFilter(Unknown Source)
	at de.symeda.sormas.ui.__EJB31_Generated__SessionFilterBean__Intf____Bean__.doFilter(Unknown Source)
	at de.symeda.sormas.ui.SessionFilter.doFilter(SessionFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:167)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.doChainInvoke(StandardPipeline.java:581)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:201)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor2961.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	... 78 common frames omitted
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method buttonClick in de.symeda.sormas.ui.samples.humansample.SampleController$$Lambda$3961/0x0000000802f53040 failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:726)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:399)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:363)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1190)
	at com.vaadin.ui.Button.fireClick(Button.java:384)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	... 82 common frames omitted
Caused by: java.lang.NullPointerException: null
	at de.symeda.sormas.ui.samples.pathogentestlink.PathogenTestListEntry.<init>(PathogenTestListEntry.java:80)
	at de.symeda.sormas.ui.samples.CollapsiblePathogenTestForm.resetCollapsedLayout(CollapsiblePathogenTestForm.java:94)
	at de.symeda.sormas.ui.samples.CollapsiblePathogenTestForm.<init>(CollapsiblePathogenTestForm.java:69)
	at de.symeda.sormas.ui.samples.humansample.SampleController.addPathogenTestComponent(SampleController.java:252)
	at de.symeda.sormas.ui.samples.humansample.SampleController.addPathogenTestComponent(SampleController.java:163)
	at de.symeda.sormas.ui.samples.humansample.SampleController.lambda$addPathogenTestButton$f825292$1(SampleController.java:323)
	at jdk.internal.reflect.GeneratedMethodAccessor2366.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:706)
	... 87 common frames omitted`

Steps to reproduce:
1. Login as Admin+Natuser
2. Open a Case that doesn't has a Sample yet
3. Click the button to add a Sample
4. Don't complete any data for the Sample just click the button Add Pathogen Test

<img width="1440" alt="Screenshot 2023-10-12 at 08 59 58" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/91872179/30aabd2d-4963-4e5a-bfb4-7ebe4106351d">

**Comment by adinaflorea9** [comment]
Web app part of the ticket has been verified. Currently blocked on the android part as Android Studio Devices do not run.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.90.0-SNAPSHOT(eb73d9d).
