### ISSUE TITLE
ClassNotFoundExceptions when starting Sormas from IntelliJ

### ISSUE THREAD

**Issue by jgwashburn** [SORMAS-Foundation/SORMAS-Project#2251]
### Bug Description

Hi, I am having some difficulty  running Sormas in the IntelliJ IDE. There are some classes that appear to be missing. Can someone advise as to how to find these missing classes? Thanks!

### Steps to Reproduce

Go through the steps listed in DEVELOPMENT_ENVIRONMENT.md using IntelliJ as IDE, then attempt to run Glassfish (Payara) IntelliJ config.

### Expected Behavior

see the login page (sormas-ui)

## Actual Behavior

IntelliJ console logs:

> /opt/payara5/glassfish/bin/asadmin start-domain --debug --domaindir /opt/domains sormas
> /usr/lib/jvm/zulu-8-amd64/bin/java -Dfile.encoding=UTF-8 -classpath /home/jwashburn/Applications/idea-IU-201.7846.76/lib/idea_rt.jar com.intellij.rt.execution.CommandLineWrapper /tmp/idea_classpath59314907 com.intellij.javaee.oss.process.JavaeeProcess 37113 com.intellij.javaee.oss.glassfish.agent.Glassfish51Agent
> [2020-06-03 07:39:52,426] Artifact sormas-ear:ear: Waiting for server connection to start artifact deployment...
> [2020-06-03 07:39:52,450] Artifact sormas-rest:war: Waiting for server connection to start artifact deployment...
> [2020-06-03 07:39:52,450] Artifact sormas-ui:war: Waiting for server connection to start artifact deployment...
> Detected server admin port: 6048
> Detected server http port: 6080
> Waiting for sormas to start .Connected to the target VM, address: '127.0.0.1:6009', transport: 'socket'
> ....
> Successfully started the domain : sormas
> domain  Location: /opt/domains/sormas
> Log File: /opt/domains/sormas/logs/server.log
> Admin Port: 6048
> Command start-domain executed successfully.
> Connected to server
> [2020-06-03 07:39:57,782] Artifact sormas-ear:ear: Artifact is being deployed, please wait...
> [2020-06-03 07:39:57,787] Artifact sormas-rest:war: Artifact is being deployed, please wait...
> [2020-06-03 07:39:57,789] Artifact sormas-ui:war: Artifact is being deployed, please wait...
> [2020-06-03 07:40:01,138] Artifact sormas-ear:ear: Error during artifact deployment. See server log for details.
> [2020-06-03 07:40:01,138] Artifact sormas-ear:ear: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while preparing the app. Please see server.log for more details.
> Exception while invoking class org.glassfish.persistence.jpa.JPADeployer prepare method : java.lang.RuntimeException: java.lang.ClassNotFoundException: org.hibernate.jpa.HibernatePersistenceProvider
> java.lang.ClassNotFoundException: org.hibernate.jpa.HibernatePersistenceProvider
> [2020-06-03 07:40:03,204] Artifact sormas-rest:war: Error during artifact deployment. See server log for details.
> [2020-06-03 07:40:03,205] Artifact sormas-rest:war: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: java.lang.ClassNotFoundException: org.slf4j.Logger. Please see server.log for more details.
> [2020-06-03 07:40:04,016] Artifact sormas-ui:war: Error during artifact deployment. See server log for details.
> [2020-06-03 07:40:04,016] Artifact sormas-ui:war: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService. Please see server.log for more details.
> 

(I could link to server log if needed, but it is rather large for this space.)

### System Details

* SORMAS version: 1.41.1

**Comment by MateStrysewskeSym** [comment]
@jgwashburn Hi! Can you attach a screenshot of the deployment tab of your server configuration?

**Comment by jgwashburn** [comment]
![Screenshot from 2020-06-05 05-48-28](https://user-images.githubusercontent.com/1228815/83878530-249fc100-a6f1-11ea-8568-c4c2d1d4bd74.png)

**Comment by MateStrysewskeSym** [comment]
Looks fine to me. @BarnaBartha do you have an idea what could cause this problem?

**Comment by BarnaBartha** [comment]
This is not an IntelliJ issue, i've had this issue with eclipse too, what is suggest is to make sure you have a clean payara domain and that 'mvn clean install' is successful from sormas-base module.

**Comment by MateStrysewskeSym** [comment]
@jgwashburn Maybe doing another ant clean and generating sources for all maven projects might help?

**Comment by xavier-calland** [comment]
I installed my development environment recently, my recent experience may help.

@jgwashburn Did you try to deploy the latest release like explained [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md#sormas-server) to validate your server install ? (Maybe it's not a problem with IntelliJ and building).
I've had some issues with recent Payara version, I finally let the `server-setup.sh` script download and install the version 5.192.

Is your postgresql server properly installed and configured (i.e. databases and user are created, extensions are installed) ? If the database is not OK, the ear will not deploy correctly.

Another thing that I missed in the doc: don't forget to execute the ant task `deploy-serverlibs` .

**Comment by jgwashburn** [comment]
Hi @xavier-calland  and @MateStrysewskeSym  thanks for responses, yes I am also using Payara version 5.192
For postgres I was able to install a sormas compatible version (10) and compile the  temporal database extension. 
But looking at the postgresql server running now, with psql, I don't see any sormas related databases or tables.
I had executed the server-setup.sh as you to refer to above, and it seemed to execute successfully , but looking at the setup.log more closely it looks like there may be a couple of errors , especially where I see ```chown: invalid user: ‘payara:payara’```
complete log attached here:
[setup.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/4774946/setup.log)

For the ant task I should run, I am not completely sure how to do that in IntelliJ , when I have a look at the Ant sidebar, it does show anything yet 
(screenshot of what I see)
![Screenshot from 2020-06-13 09-29-46](https://user-images.githubusercontent.com/1228815/84573986-a8dcee80-ad58-11ea-8634-19eefd966c27.png)

**Comment by BarnaBartha** [comment]
To see the ant task you have to add it with the '+' (the file sormas-base/build.xml) 
By clean domain I understand having the /lib /applications /logs folders emptied. (or even better remove the domain altogether and recreate it - also make sure the certificate is correct - copy the one from the default domain1 eg.: payara5/glassfish/domains/domain1/config/cacerts.jks)
Also from your logs I can see that the ear is not deployed correctly as classes from it cannot be loaded for this make sure your db is correctly set up and that you deploy the artifact from within intellij's payara server and not an external source.

**Comment by xavier-calland** [comment]
@jgwashburn in the `setup.log` I see :

```
--- Enter a password for the new database user 'sormas_user': --- Enter a password for the new database user 'sormas_user': --- Enter a password for the new database user 'sormas_user': --- Enter a password for the new database user 'sormas_user': Password: Password: 

su: Authentication failure
su: Authentication failure
```

I think `su: Authentication failure` means the script can't `su` to postgres, so the database is not initialized.
Did you run `server-setup.sh` as `root` ?

**Comment by jgwashburn** [comment]
You are right, I cleared the sormas domain, and reran server-setup.sh as root, and everything looks good now in terms of the databases being set up. Also , I ran the ant task deploy-serverlibs.
Now the only problem I see when starting sormas from IntelliJ is "Address localhost:6048 is already is use" - I think this means that I have Payara running independently of IntellJ, and I need to find a way to stop it running and keep it from restarting.

**Comment by xavier-calland** [comment]
`server-setup.sh` starts the server.
You can stop it running `service payara-sormas stop` or `${DOMAIN_DIR}/stop-payara-sormas.sh`.

The `server-setup.sh` is not really dev compliant, I think it can be useful to have a light script with no user creation, no service creation, using docker image for postgresql, using a $HOME based path.

@MateStrysewskeSym what do you think ? I can propose such a script.

**Comment by MateStrysewskeSym** [comment]
@xavier-calland First of all, thanks for providing so much support here! What exactly would the purpose of such a script be?

**Comment by xavier-calland** [comment]
Setup a Sormas dev environment : `root` access is not needed
- use `${HOME}` as `${ROOT_PREFIX}`
- install Payara in a custom path if needed (like `server-setup.sh`)
- configure Sormas domain in a custom path (like `server-setup.sh`)
- skip DB setup : use docker image
- run ant task

**Comment by MateStrysewskeSym** [comment]
@xavier-calland Ah, I see. Yeah, I guess that's a good idea!

**Comment by jgwashburn** [comment]
Thanks @xavier-calland  and @MateStrysewskeSym for your support .
I think I am almost there.
I stopped the (external to IntelliJ) Payara server with ```service payara-sormas stop```

However now when I start the sormas configuration from IntelliJ, it is asking me for a master password:

```

/usr/lib/jvm/zulu-8-amd64/bin/java -Dfile.encoding=UTF-8 -classpath /home/jwashburn/Applications/idea-IU-201.7846.76/lib/idea_rt.jar com.intellij.rt.execution.CommandLineWrapper /tmp/idea_classpath1047532499 com.intellij.javaee.oss.process.JavaeeProcess 45769 com.intellij.javaee.oss.glassfish.agent.Glassfish51Agent
/opt/payara5/glassfish/bin/asadmin start-domain --domaindir /opt/domains sormas
Detected server admin port: 6048
Detected server http port: 6080
[2020-06-16 07:02:06,963] Artifact sormas-ear:ear: Waiting for server connection to start artifact deployment...
[2020-06-16 07:02:06,963] Artifact sormas-rest:war: Waiting for server connection to start artifact deployment...
[2020-06-16 07:02:06,963] Artifact sormas-ui:war: Waiting for server connection to start artifact deployment...
Enter master password (3) attempt(s) remain)>

Sorry, incorrect master password, retry
Enter master password (2) attempt(s) remain)>

Sorry, incorrect master password, retry
Enter master password (1) attempt(s) remain)>

Command start-domain failed.
Number of attempts (3) exhausted, giving up


```
I am not clear what resource the master password is for , or what I should enter.  I tried the what I entered from server_setup.sh but that was not accepted.

**Comment by xavier-calland** [comment]
I'm not sure what this "master password" is.
You have to set the admin password for the payara server in the IntelliJ task (default empty).
Can this "master password" refer to you local account password or a password to unlock IntelliJ vault ?

**Comment by MateStrysewskeSym** [comment]
@jgwashburn That's a problem with the (I believe) keystore.jks file in the payara domain. Can you try to replace it with an empty keystore.jks file and see whether it works?

**Comment by jgwashburn** [comment]
Yes, the master password message appears be related to asadmin. I had gotten around it by doing  ```chmod``` on /opt/domains/sormas/config so that that dir could be read by a user other than "payara" . Now I see further permission issues on other files in the domain dir , getting around them for now with ```chmod```.

**Comment by jgwashburn** [comment]
So I was able to get around the permissions problems that I was seeing,  as logged in the file ```/opt/domains/sormas/logs/server.log```
by performing a recursive chmod on domain dir ```/opt/domains/sormas``` .

However when trying again to start sormas from IntelliJ, sormas still does not start, and now I see a new type of error message in that same log file, as follows:

```
[2020-07-26T14:37:52.263-0700] [Payara 5.192] [SEVERE] [NCLS-CORE-00016] [javax.enterprise.system.core] [tid: _ThreadID=32 _ThreadName=RunLevelControllerThread-1595799471752] [timeMillis: 1595799472263] [levelValue: 1000] [[
  Startup service failed to start
MultiException stack 1 of 2
com.sun.enterprise.module.ResolveError: Failed to start OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [84]], State = [RESOLVED]
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:217)
	at org.jvnet.hk2.osgiadapter.OsgiPopulatorPostProcessor$1.loadClass(OsgiPopulatorPostProcessor.java:78)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2248)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.framework.BundleException: Unable to acquire global lock for resolve. Unresolved requirements: []
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.jvnet.hk2.osgiadapter.OSGiModuleImpl.start(OSGiModuleImpl.java:209)
	... 10 more
MultiException stack 2 of 2
java.lang.IllegalStateException: Could not load descriptor SystemDescriptor(
	implementation=fish.payara.appserver.micro.services.PayaraInstanceImpl
	name=payara-instance
	contracts={fish.payara.appserver.micro.services.PayaraInstanceImpl,fish.payara.micro.PayaraInstance}
	scope=org.glassfish.hk2.runlevel.RunLevel
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=runLevelValue={10},Bundle-SymbolicName={fish.payara.micro.payara-micro-service},Bundle-Version={5.192.0}
	rank=0
	loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [fish.payara.micro.payara-micro-service [84]], State = [RESOLVED],1648341459)
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=863
	locatorId=0
	identityHashCode=92051808
	reified=false)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.loadClass(ServiceLocatorImpl.java:2257)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:478)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.isWouldBlockRightNow(CurrentTaskFuture.java:1194)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1230)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]

```
Not sure what global lock is being referred to. I had rebooted Linux box so there should not be multiple instances of a JVM involved.

**Comment by benchaabaner** [comment]
Hi,

I have the same issues while trying to deploy from intellj.
I have followed all the steps above but i can't seem to figure out the problem.

Here are my server logs : 
[server.log](https://github.com/hzi-braunschweig/SORMAS-Project/files/5155628/server.log)

and here is my intellij output : 
`C:\opt\payara5\glassfish\bin\asadmin.bat start-domain --domaindir C:\opt\domains sormas
"C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" -Dfile.encoding=windows-1252 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.4\lib\idea_rt.jar" com.intellij.rt.execution.CommandLineWrapper C:\Users\benchaabaner\AppData\Local\Temp\idea_classpath1381739264 com.intellij.javaee.oss.process.JavaeeProcess 51193 com.intellij.javaee.oss.glassfish.agent.Glassfish51Agent
Detected server admin port: 6048
[2020-09-01 12:12:59,250] Artifact sormas-ear:ear: Waiting for server connection to start artifact deployment...
[2020-09-01 12:12:59,254] Artifact sormas-rest:war: Waiting for server connection to start artifact deployment...
[2020-09-01 12:12:59,254] Artifact sormas-ui:war: Waiting for server connection to start artifact deployment...
Detected server http port: 6080
Attempting to start sormas.... Please look at the server log for more details.....
Connected to server
[2020-09-01 12:13:41,326] Artifact sormas-ear:ear: Artifact is being deployed, please wait...
[2020-09-01 12:13:41,333] Artifact sormas-rest:war: Artifact is being deployed, please wait...
[2020-09-01 12:13:41,337] Artifact sormas-ui:war: Artifact is being deployed, please wait...
[2020-09-01 12:14:24,694] Artifact sormas-ear:ear: Error during artifact deployment. See server log for details.
[2020-09-01 12:14:24,699] Artifact sormas-ear:ear: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while preparing the app. Please see server.log for more details.
Exception while invoking class org.glassfish.persistence.jpa.JPADeployer prepare method : java.lang.RuntimeException: java.lang.ClassNotFoundException: org.hibernate.jpa.HibernatePersistenceProvider
java.lang.ClassNotFoundException: org.hibernate.jpa.HibernatePersistenceProvider
[2020-09-01 12:15:59,123] Artifact sormas-rest:war: Error during artifact deployment. See server log for details.
[2020-09-01 12:15:59,123] Artifact sormas-rest:war: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory. Please see server.log for more details.
[2020-09-01 12:16:25,563] Artifact sormas-ui:war: Error during artifact deployment. See server log for details.
[2020-09-01 12:16:25,564] Artifact sormas-ui:war: java.io.IOException: com.sun.enterprise.admin.remote.RemoteFailureException: Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService. Please see server.log for more details.`
