### ISSUE TITLE
SormasErrorHandler: Enhance backend bug reports which now drop root cause position

### ISSUE THREAD

**Issue by StefanKock** [SORMAS-Foundation/SORMAS-Project#2498]
### Problem Description
After doing #2352, I now notice that for example the StackTraces of #2326 now are shorter:  The StackTrace now is also missing the point where the Exception happens, seems to break one method call before.

### Proposed Change
Review changes of #2352 and change it to not to drop the root cause method and line of code.

### Additional Information
Version: 1.43.x

**Comment by StefanKock** [comment]
A typical StackTrace containing the Problem: The call of CaseFacadeEjb.onCaseChanged with the LOC where the NPE is happening is missing.
[Full StackTrace.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4945969/Full.StackTrace.txt)

**Comment by StefanKock** [comment]
I was not able to reproduce this. 
Problematic StackTrace:
```
...
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:664)
at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:509)
at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4761)
at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2147)
... 148 more
Caused by: java.lang.NullPointerException

----------END server-side stack trace----------
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
...
```
Testing this by throwing a NPE at the end of the method is showing what I wanted (`onCaseChanged(CaseFacadeEjb.java:1496)`):
```
...
Caused by: javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean: java.lang.NullPointerException
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:615)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:485)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4562)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2111)
	... 151 more
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.onCaseChanged(CaseFacadeEjb.java:1496)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 149 more

----------END server-side stack trace----------
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
...

**Comment by StefanKock** [comment]
This should be reevaluated after 1.45 released and used.
